-- ============================================================================
-- Legacy baseline: public.post_analyses, public.completed_post_analyses
--
-- This migration reproduces the EXACT structure of the hosted legacy
-- sentiment-analysis schema, as captured via
-- supabase/scripts/inspect_legacy_analysis_schema.sql run against the
-- hosted project on 2026-09-02.
--
-- Purpose: give a disposable/staging/local Supabase instance the same
-- legacy objects that already exist in production, so the additive V2
-- migration (post_analyses_v2) can be developed and tested against a
-- realistic baseline.
--
-- This migration must NEVER be applied to the hosted/production project,
-- since these objects already exist there. All statements use IF NOT
-- EXISTS / OR REPLACE guards and are not expected to run against a
-- database where the legacy objects are already present.
--
-- Do not edit this file to "improve" the legacy schema. If the legacy
-- schema needs to change, that is a separate, explicit migration on top
-- of this baseline.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Table: public.post_analyses
-- ---------------------------------------------------------------------------
create table if not exists public.post_analyses (
    id bigint generated by default as identity primary key,
    post_uri text not null unique,
    sentiment text,
    score numeric(3, 2),
    emotions jsonb not null default '[]'::jsonb,
    topics jsonb not null default '[]'::jsonb,
    ai_tooling_stance text,
    confidence numeric(3, 2),
    rationale text,
    model text not null,
    prompt_version text not null,
    status text not null default 'pending',
    retry_count integer not null default 0,
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    processed_at timestamptz,
    constraint post_analyses_confidence_check check (confidence >= 0::numeric and confidence <= 1::numeric),
    constraint post_analyses_retry_count_check check (retry_count >= 0),
    constraint post_analyses_score_check check (score >= 0::numeric and score <= 1::numeric),
    constraint post_analyses_status_check check (status = any (array['pending'::text, 'processing'::text, 'complete'::text, 'failed'::text]))
);

create index if not exists post_analyses_created_at_idx on public.post_analyses using btree (created_at desc);
create index if not exists post_analyses_post_uri_idx on public.post_analyses using btree (post_uri);
create index if not exists post_analyses_status_idx on public.post_analyses using btree (status);

alter table public.post_analyses enable row level security;

drop policy if exists "Allow anon read completed analyses" on public.post_analyses;
create policy "Allow anon read completed analyses"
    on public.post_analyses
    for select
    to anon
    using (status = 'complete'::text);

drop policy if exists "post_analyses_service_role_full" on public.post_analyses;
create policy "post_analyses_service_role_full"
    on public.post_analyses
    for all
    to service_role
    using (true)
    with check (true);

-- ---------------------------------------------------------------------------
-- View: public.completed_post_analyses
-- ---------------------------------------------------------------------------
create or replace view public.completed_post_analyses as
select
    pa.post_uri,
    pa.sentiment,
    pa.score,
    pa.emotions,
    pa.topics,
    pa.ai_tooling_stance,
    pa.confidence,
    pa.rationale,
    pa.model,
    pa.prompt_version,
    pa.created_at,
    pa.processed_at,
    bp.post_text,
    bp.author_handle,
    bp.original_language,
    bp.published_at,
    bp.source_url
from public.post_analyses pa
join public.bluesky_posts bp on pa.post_uri = bp.uri
where pa.status = 'complete'::text;

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------
create or replace function public.mark_analysis_failed(p_post_uri text, p_error_message text)
returns void
language plpgsql
as $function$
begin
  update public.post_analyses
  set
    status = 'failed',
    retry_count = retry_count + 1,
    error_message = p_error_message,
    updated_at = now()
  where post_uri = p_post_uri;
end;
$function$;

create or replace function public.ensure_analysis_records(p_post_uris text[])
returns void
language plpgsql
as $function$
begin
  insert into public.post_analyses (post_uri, status, model, prompt_version, sentiment, confidence, rationale)
  select uri, 'pending', 'mock', 'v1', 'pending', 0, 'pending'
  from unnest(p_post_uris) as uri
  where not exists (select 1 from public.post_analyses where post_uri = uri)
  on conflict do nothing;
end;
$function$;

create or replace function public.update_analysis_result(
    p_post_uri text,
    p_sentiment text,
    p_score numeric,
    p_emotions jsonb,
    p_topics jsonb,
    p_ai_stance text,
    p_confidence numeric,
    p_rationale text,
    p_model text,
    p_prompt_version text
)
returns void
language plpgsql
as $function$
begin
  update public.post_analyses
  set
    sentiment = p_sentiment,
    score = p_score,
    emotions = p_emotions,
    topics = p_topics,
    ai_tooling_stance = p_ai_stance,
    confidence = p_confidence,
    rationale = p_rationale,
    model = p_model,
    prompt_version = p_prompt_version,
    status = 'complete',
    processed_at = now(),
    updated_at = now(),
    error_message = null
  where post_uri = p_post_uri;
end;
$function$;

create or replace function public.claim_posts_for_analysis(batch_size integer default 10, max_retries integer default 3)
returns table(post_uri text, post_text text, author_handle text, original_language text)
language plpgsql
as $function$
begin
  return query
  with claimed as (
    update public.post_analyses pa
    set
      status = 'processing',
      updated_at = now()
    where pa.post_uri in (
      select pa2.post_uri from public.post_analyses pa2
      where (pa2.status = 'pending' or (pa2.status = 'failed' and pa2.retry_count < max_retries))
      order by pa2.updated_at asc
      limit batch_size
      for update skip locked
    )
    returning pa.post_uri
  )
  select
    claimed.post_uri,
    bp.post_text,
    bp.author_handle,
    bp.original_language
  from claimed
  join public.bluesky_posts bp on claimed.post_uri = bp.uri;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Grants (observed on hosted project)
-- ---------------------------------------------------------------------------
-- post_analyses: anon has no privileges (all access goes through the
-- completed_post_analyses view's SELECT grant and the RLS policy above);
-- service_role has no table-level grants either -- it relies on RLS
-- policy "post_analyses_service_role_full" plus its role bypassing RLS
-- is NOT assumed; grants observed showed no explicit GRANT rows for
-- service_role on post_analyses beyond default ownership. No additional
-- GRANT statements are required to reproduce the observed state, since
-- table owner (postgres) already has full privileges by default.

grant select on public.completed_post_analyses to anon;
grant select on public.completed_post_analyses to authenticated;
