-- ============================================================================
-- Additive V2 schema: public.post_analyses_v2
--
-- Isolated storage for the manually invoked Foundry one-post sentiment
-- enrichment slice. This migration is purely additive: it does not alter,
-- drop, or mutate any existing legacy object (post_analyses,
-- completed_post_analyses, bluesky_posts, or their triggers/functions).
--
-- Scope for this slice only: FK integrity, uniqueness, allowed enum
-- values, and scalar range checks needed for a single manual
-- eligibility lookup and a single completed-result validation read.
-- Queue leases, retry orchestration, attempt ledgers, schedules,
-- rollups, and concurrent-claim behavior are explicitly out of scope
-- here (see plan step 6, deferred).
-- ============================================================================

create table if not exists public.post_analyses_v2 (
    id bigint generated by default as identity primary key,
    post_uri text not null references public.bluesky_posts (uri),
    prompt_version text not null,
    provider text,
    deployment text,
    model text,
    sentiment text,
    sentiment_score numeric(4, 3),
    emotions jsonb not null default '[]'::jsonb,
    topics jsonb not null default '[]'::jsonb,
    tools_mentioned jsonb not null default '[]'::jsonb,
    ai_tooling_stance text,
    confidence numeric(4, 3),
    rationale text,
    status text not null default 'pending',
    retry_count integer not null default 0,
    error_message text,
    locked_until timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    processed_at timestamptz,

    constraint post_analyses_v2_post_uri_prompt_version_key unique (post_uri, prompt_version),

    constraint post_analyses_v2_status_check check (
        status = any (array['pending'::text, 'processing'::text, 'complete'::text, 'failed'::text])
    ),
    constraint post_analyses_v2_sentiment_check check (
        sentiment is null or sentiment = any (array['positive'::text, 'negative'::text, 'neutral'::text, 'mixed'::text])
    ),
    constraint post_analyses_v2_ai_tooling_stance_check check (
        ai_tooling_stance is null or ai_tooling_stance = any (
            array['positive'::text, 'negative'::text, 'neutral'::text, 'mixed'::text, 'not_applicable'::text]
        )
    ),
    constraint post_analyses_v2_sentiment_score_check check (
        sentiment_score is null or (sentiment_score >= -1::numeric and sentiment_score <= 1::numeric)
    ),
    constraint post_analyses_v2_confidence_check check (
        confidence is null or (confidence >= 0::numeric and confidence <= 1::numeric)
    ),
    constraint post_analyses_v2_retry_count_check check (retry_count >= 0),

    -- Provenance must be present once a result is persisted as complete.
    constraint post_analyses_v2_complete_provenance_check check (
        status <> 'complete'
        or (
            coalesce(provider, '') <> ''
            and coalesce(deployment, '') <> ''
            and coalesce(model, '') <> ''
        )
    )
);

-- Eligibility lookup: find posts inserted after the V2 cutoff with no
-- existing (post_uri, prompt_version) result for a given prompt version.
create index if not exists post_analyses_v2_post_uri_idx on public.post_analyses_v2 using btree (post_uri);
create index if not exists post_analyses_v2_status_idx on public.post_analyses_v2 using btree (status);
create index if not exists post_analyses_v2_created_at_idx on public.post_analyses_v2 using btree (created_at desc);

alter table public.post_analyses_v2 enable row level security;

-- No anonymous access of any kind; only service_role (server-side worker)
-- may read/write this table in this slice.
revoke all on public.post_analyses_v2 from anon;
revoke all on public.post_analyses_v2 from authenticated;

drop policy if exists "post_analyses_v2_service_role_full" on public.post_analyses_v2;
create policy "post_analyses_v2_service_role_full"
    on public.post_analyses_v2
    for all
    to service_role
    using (true)
    with check (true);

grant all on public.post_analyses_v2 to service_role;
grant usage, select on sequence public.post_analyses_v2_id_seq to service_role;

-- ---------------------------------------------------------------------------
-- Development-only validation view.
--
-- Joins a completed V2 result to its bluesky_posts row so the one-post
-- manual test can be inspected. Not exposed to anon/authenticated and not
-- wired into the dashboard; this is a development/debugging surface only.
-- ---------------------------------------------------------------------------
create or replace view public.post_analyses_v2_dev_validation as
select
    v2.id,
    v2.post_uri,
    v2.prompt_version,
    v2.provider,
    v2.deployment,
    v2.model,
    v2.sentiment,
    v2.sentiment_score,
    v2.emotions,
    v2.topics,
    v2.tools_mentioned,
    v2.ai_tooling_stance,
    v2.confidence,
    v2.rationale,
    v2.status,
    v2.retry_count,
    v2.error_message,
    v2.created_at,
    v2.processed_at,
    bp.post_text,
    bp.author_handle,
    bp.original_language,
    bp.published_at,
    bp.source_url
from public.post_analyses_v2 v2
join public.bluesky_posts bp on v2.post_uri = bp.uri
where v2.status = 'complete';

revoke all on public.post_analyses_v2_dev_validation from anon;
revoke all on public.post_analyses_v2_dev_validation from authenticated;
grant select on public.post_analyses_v2_dev_validation to service_role;
